In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\snsha\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\snsha\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\snsha\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\snsha\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\snsha\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\snsha\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: C:\Users\snsha\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'customer_shopping_behavior.csv'

In [2]:
df.head()

NameError: name 'df' is not defined

In [4]:
import os

print(os.getcwd())
print(os.listdir())

C:\Users\snsha
['-1.14-windows.xml', '.anaconda', '.android', '.cache', '.cargo', '.codeium', '.conda', '.condarc', '.continuum', '.cursor', '.dbus-keyrings', '.eclipse', '.emulator_console_auth_token', '.gradle', '.ipynb_checkpoints', '.ipython', '.jupyter', '.matplotlib', '.ms-ad', '.node_repl_history', '.p2', '.python_history', '.rustup', '.streamlit', '.vscode', '01diagram.drawio', '185-Nanded-2002 list (Ali Khan Sahab List Sr N0-694)-page no-18.pdf', '202 Voter List DUDHAD_178-1.pdf', '202 Voter List DUDHAD_178-2.pdf', '3D Objects', 'AGD CARD FORMAT.pdf', 'anaconda3', 'AndroidStudioProjects', 'AppData', 'Application Data', 'Application_form_HCLTFP1920716.pdf', 'AppMods', 'arff converter', 'aws certificate.pdf', 'aws solution architcure certificate', 'Book1.twb', 'certificate excel.pdf', 'college project', 'Contacts', 'Cookies', 'Cover_Letter.pdf', 'CS123_lec07_Finite_State_Machine.pdf', 'cs50', 'customer_shopping_analysis', 'cv(BI).pdf', 'DataWarehouse', 'DBMS(notes).pdf', 'DBMS.pdf', 'dbms01.pdf', 'dbt certificate.pdf', 'DC Practice', 'demo1.pdf', 'Desktop', 'Documents', 'Downloads', 'DSA (IMP).pdf', 'DWH.drawio', 'dwh_project', 'eclipse', 'eclipse-workspace', 'eda certificate.pdf', 'etl_pipeline', 'exampledemo.pdf', 'excel understanding certificate.pdf', 'Favorites', 'gold.dim_customers.csv', 'gold.dim_customers1.csv', 'gold.dim_products.csv', 'gold.fact_sales.csv', 'gpt consulting guide.pdf', 'HouseData.xlsx', 'ICICI BANK APPLICATION.pdf', 'IntelGraphicsProfiles', 'Introduction to Software Engineering.docx', 'Java.pdf', 'JAVA01.pdf', 'JN', 'ks-projects-201612.csv', 'Learning data structures and algorithms.docx', 'Links', 'Local Settings', 'LTR.pdf', 'Material', 'MC25110725 Application Print.pdf', 'MCA_Pro_Merit_2025_26.pdf', 'Meta Verification Request – Nandigram Times.pdf', 'ML Projects', 'Music', 'My Documents', 'MYSQL PASSWORD.docx', 'NetHood', 'New draw', 'newfile.py', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{5e317970-02cc-11f0-af46-9a4839e7101d}.TM.blf', 'NTUSER.DAT{5e317970-02cc-11f0-af46-9a4839e7101d}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{5e317970-02cc-11f0-af46-9a4839e7101d}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'Online Retail (Cleaned data).xlsx', 'Online Retail.xlsx', 'portfolio', 'PowerBI', 'practice2.pbix', 'practicepowerbi1.pbix', 'practive.xlsx', 'PrintHood', 'python data analysis project customer_shopping_behavior_analysis', 'pythonproject001', 'python_project', 'Q 01.docx', 'Question01.pbix', 'Recent', 'Recorded Calls', 'Review of the Fundamental Principles of DBMS.docx', 'RN', 'Sales Data', 'sales-forecasting-project', 'salesdata (dashboard).csv', 'Salesdata.csv', 'Saved Games', 'ScStore', 'Searches', 'sem 2.pdf', 'SendTo', 'Shafiya Naaz 01resume.pdf', 'Shafiya Naaz 02.docx', 'Shafiya Naaz 2cv.pdf', 'Shafiya(CV).pdf', 'shafiya(cv_).pdf', 'shafiya-cv.pdf', 'Shafiya.cv.pdf', 'Shafiya.CV1.pdf', 'shafiya_cv.pdf', 'Spam Email Classifier', 'SQL', 'sql-ultimate-course-main', 'Start Menu', 'Tableau Data', 'Templates', 'Time Series Project', 'tipsss.docx', 'TWO_CENTURIES_OF_UM_RACES.csv', 'Untitled.ipynb', 'untitled.py', 'Untitled1.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Untitled4.ipynb', 'Videos', 'wekafiles']

In [5]:
import pandas as pd
df = pd.read_csv('customer_shopping_analysis/customer_shopping_behavior.csv')

In [6]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [12]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [14]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64